LPD-40374 Before deleting a group, prevent deleting LayoutPageTemplateCollections that have already been deleted, because they were children of other LayoutPageTemplateCollections
Otherwise, the following exception may be thrown during tests making below test flaky.

com.liferay.headless.admin.site.resource.v1_0.test.DisplayPageTemplateFolderResourceTest > testPostSiteSiteByExternalReferenceCodeDisplayPageTemplateFolder FAILED
    com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.layout.page.template.exception.NoSuchPageTemplateCollectionException: No LayoutPageTemplateCollection exists with the primary key 38747
    	at com.liferay.layout.page.template.internal.model.listener.GroupModelListener.onBeforeRemove(GroupModelListener.java:81)
    	at com.liferay.layout.page.template.internal.model.listener.GroupModelListener.onBeforeRemove(GroupModelListener.java:29)
    	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.removeByFunction(BasePersistenceImpl.java:672)
    	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:653)
    	at com.liferay.portal.service.impl.GroupLocalServiceImpl.deleteGroup(GroupLocalServiceImpl.java:1232)
    	at sun.reflect.GeneratedMethodAccessor1666.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
    	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
    	at com.sun.proxy.$Proxy69.deleteGroup(Unknown Source)
    	at com.liferay.portal.kernel.service.GroupLocalServiceUtil.deleteGroup(GroupLocalServiceUtil.java:259)
    	at com.liferay.portal.kernel.test.util.GroupTestUtil.deleteGroup(GroupTestUtil.java:244)
    	at com.liferay.headless.admin.site.resource.v1_0.test.BaseDisplayPageTemplateFolderResourceTestCase.tearDown(BaseDisplayPageTemplateFolderResourceTestCase.java:118)
    	at sun.reflect.GeneratedMethodAccessor4145.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
    	at java.lang.Thread.run(Thread.java:750)
    Caused by: com.liferay.layout.page.template.exception.NoSuchPageTemplateCollectionException: No LayoutPageTemplateCollection exists with the primary key 38747
    	at com.liferay.layout.page.template.service.persistence.impl.LayoutPageTemplateCollectionPersistenceImpl.findByPrimaryKey(LayoutPageTemplateCollectionPersistenceImpl.java:8960)
    	at com.liferay.layout.page.template.service.persistence.impl.LayoutPageTemplateCollectionPersistenceImpl.findByPrimaryKey(LayoutPageTemplateCollectionPersistenceImpl.java:8979)
    	at com.liferay.layout.page.template.service.base.LayoutPageTemplateCollectionLocalServiceBaseImpl.getLayoutPageTemplateCollection(LayoutPageTemplateCollectionLocalServiceBaseImpl.java:312)
    	at com.liferay.layout.page.template.service.impl.LayoutPageTemplateCollectionLocalServiceImpl.deleteLayoutPageTemplateCollection(LayoutPageTemplateCollectionLocalServiceImpl.java:239)
    	at sun.reflect.GeneratedMethodAccessor4114.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
    	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
    	at com.sun.proxy.$Proxy849.deleteLayoutPageTemplateCollection(Unknown Source)
    	at com.liferay.layout.page.template.internal.model.listener.GroupModelListener.onBeforeRemove(GroupModelListener.java:46)
    	... 50 more